name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Setup pub.dev credentials
        uses: dart-lang/setup-dart@v1

      - name: Publish
        run: flutter pub publish --force
